apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentimentops
  labels:
    app: sentimentops

spec:
  replicas: 2
  selector:
    matchLabels: 
      app: sentimentops
  template: 
    metadata:
      labels: 
        app: sentimentops
    spec: 
      containers:
        - name: sentimentops
          image: 784608887303.dkr.ecr.us-east-1.amazonaws.com/sentimentops:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "250Mi"
              cpu: "1"
          env:
            - name: DAGSHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: capstone-secret
                  key: DAGSHUB_TOKEN

---

apiVersion: v1
kind: Service
metadata:
  name: sentimentops-service
spec:
  type: LoadBalancer
  selector:
    app: sentimentops
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
